// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Outcome of an age verification request.
enum AgeVerificationStatus {
  /// The platform confirms the user meets the minimum age requirement.
  ///
  /// Android: parental controls indicate the account is above the threshold.
  /// iOS: the declared age range satisfies all configured age gates.
  verified,
  /// The platform could not produce an age signal.
  ///
  /// Common reasons:
  /// - Parental controls are not configured (Android)
  /// - Verification data is unavailable for this account
  /// - The API is unsupported in the user's region
  unknown,
  /// The user chose not to share their age (iOS only).
  ///
  /// The user was prompted but explicitly declined to reveal their age
  /// range to the app.
  declined,
  /// The user is below the age threshold or under parental supervision.
  ///
  /// Android: the account is family-managed and does not meet the age
  /// requirement. iOS: the declared age range falls below the configured gates.
  supervised,
  /// Supervised user — guardian approval is pending (Android only).
  ///
  /// The account is family-managed and an access request has been dispatched
  /// to the guardian. The guardian has not yet responded.
  supervisedApprovalPending,
  /// Supervised user — guardian denied the request (Android only).
  ///
  /// The account is family-managed and the guardian has explicitly
  /// rejected the access request.
  supervisedApprovalDenied,
  /// Age was self-declared through Google Play (Android only).
  ///
  /// The user completed Google Play's age declaration flow.
  /// Requires age-signals 0.0.3 or later.
  declared,
}

/// Who provided the age declaration (iOS only).
enum AgeDeclarationSource {
  /// The user declared their own age.
  selfDeclared,
  /// A guardian declared the age on the user's behalf via Family Sharing.
  guardianDeclared,
}

/// Error codes reported when an age verification call fails.
enum AgeVerificationErrorCode {
  /// The Age Signals API is not available on this device or region.
  apiNotAvailable,
  /// Google Play Services encountered an error.
  playServicesError,
  /// A network error prevented the request from completing.
  networkError,
  /// The installed Play Services SDK is too old to support Age Signals.
  sdkVersionOutdated,
  /// [AgeVerificationApi.verifyAge] was called before [AgeVerificationApi.initialize].
  notInitialized,
  /// An unexpected error occurred during initialisation.
  initError,
  /// An unclassified API error occurred.
  apiError,
}

/// Mock result returned by [AgeVerificationApi.verifyAge] during testing.
///
/// Pass to [AgeVerificationApi.initialize] to enable mock mode on both
/// platforms. The native API is not called — [verifyAge] returns this data
/// directly. Pass `null` to [initialize] for real production behaviour.
class AgeVerificationMockConfig {
  AgeVerificationMockConfig({
    required this.status,
    this.ageLower,
    this.ageUpper,
    this.source,
    this.installId,
  });

  /// The status to return from [AgeVerificationApi.verifyAge].
  AgeVerificationStatus status;

  /// Mocked inclusive lower bound of the age range.
  int? ageLower;

  /// Mocked inclusive upper bound of the age range.
  int? ageUpper;

  /// Mocked declaration source (iOS field).
  AgeDeclarationSource? source;

  /// Mocked install identifier (Android field).
  String? installId;

  List<Object?> _toList() {
    return <Object?>[
      status,
      ageLower,
      ageUpper,
      source,
      installId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AgeVerificationMockConfig decode(Object result) {
    result as List<Object?>;
    return AgeVerificationMockConfig(
      status: result[0]! as AgeVerificationStatus,
      ageLower: result[1] as int?,
      ageUpper: result[2] as int?,
      source: result[3] as AgeDeclarationSource?,
      installId: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AgeVerificationMockConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(ageLower, other.ageLower) && _deepEquals(ageUpper, other.ageUpper) && _deepEquals(source, other.source) && _deepEquals(installId, other.installId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Data returned by the platform after querying age signals.
///
/// Wraps the raw response from the native age verification API.
/// Fields vary by platform; expect nulls where a platform does not
/// provide a particular value or when the user withholds consent.
class AgeVerificationResult {
  AgeVerificationResult({
    required this.status,
    this.ageLower,
    this.ageUpper,
    this.source,
    this.installId,
  });

  /// The outcome of the age check as reported by the platform.
  AgeVerificationStatus status;

  /// Inclusive lower bound of the estimated age range.
  ///
  /// iOS: present when the user grants permission to share their age bracket.
  /// Android: present for family-managed accounts via parental controls.
  /// Null when the user opts out (iOS) or the platform cannot supply the value.
  int? ageLower;

  /// Inclusive upper bound of the estimated age range.
  ///
  /// iOS: present when the user grants permission to share their age bracket.
  /// Android: present for family-managed accounts via parental controls.
  /// Null when the user opts out (iOS) or the platform cannot supply the value.
  int? ageUpper;

  /// Who provided the age declaration (iOS only).
  ///
  /// Distinguishes between an age declared by the user themselves and one
  /// entered by a guardian through Family Sharing. Null on Android or when
  /// the user has not shared their age.
  AgeDeclarationSource? source;

  /// Stable identifier for this app install (Android only).
  ///
  /// Intended for compliance logging and audit trails.
  /// Always null on iOS.
  String? installId;

  List<Object?> _toList() {
    return <Object?>[
      status,
      ageLower,
      ageUpper,
      source,
      installId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AgeVerificationResult decode(Object result) {
    result as List<Object?>;
    return AgeVerificationResult(
      status: result[0]! as AgeVerificationStatus,
      ageLower: result[1] as int?,
      ageUpper: result[2] as int?,
      source: result[3] as AgeDeclarationSource?,
      installId: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AgeVerificationResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(ageLower, other.ageLower) && _deepEquals(ageUpper, other.ageUpper) && _deepEquals(source, other.source) && _deepEquals(installId, other.installId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AgeVerificationStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is AgeDeclarationSource) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is AgeVerificationErrorCode) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is AgeVerificationMockConfig) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is AgeVerificationResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AgeVerificationStatus.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AgeDeclarationSource.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : AgeVerificationErrorCode.values[value];
      case 132:
        return AgeVerificationMockConfig.decode(readValue(buffer)!);
      case 133:
        return AgeVerificationResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AgeVerificationApi {
  /// Constructor for [AgeVerificationApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AgeVerificationApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Initializes the platform age signals manager.
  ///
  /// Pass [mockConfig] to enable mock mode — both platforms will return the
  /// supplied result from [verifyAge] without calling the native API.
  /// Omit [mockConfig] (or pass null) for real production behaviour.
  Future<void> initialize({AgeVerificationMockConfig? mockConfig}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.age_verification.AgeVerificationApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mockConfig]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<AgeVerificationResult> verifyAge(List<int>? ageGates) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.age_verification.AgeVerificationApi.verifyAge$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[ageGates]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AgeVerificationResult;
  }
}
