name: age_verification
description: "A Flutter plugin for querying platform age signals via Google Play Age Signals on Android and Apple DeclaredAgeRange on iOS, for regional age verification compliance."
version: 0.2.7
homepage: https://github.com/gktirkha/age_verification
repository: https://github.com/gktirkha/age_verification

topics:
  - age-verification
  - age-range
  - age-signals
  - declared-age-range

environment:
  sdk: ^3.10.7
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.18.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pigeon: ^26.3.4

flutter:
  plugin:
    platforms:
      android:
        package: com.gtirkha.age_verification
        pluginClass: AgeVerificationPlugin
      ios:
        pluginClass: AgeVerificationPlugin
  config:
    enable-swift-package-manager: true
