// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsAgeVerificationApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashAgeVerificationApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsAgeVerificationApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsAgeVerificationApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsAgeVerificationApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsAgeVerificationApi(lhsKey, rhsKey) {
          if deepEqualsAgeVerificationApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsAgeVerificationApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashAgeVerificationApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashAgeVerificationApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashAgeVerificationApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashAgeVerificationApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashAgeVerificationApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashAgeVerificationApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Outcome of an age verification request.
enum AgeSignalsStatus: Int {
  /// The platform confirms the user meets the minimum age requirement.
  ///
  /// Android: parental controls indicate the account is above the threshold.
  /// iOS: the declared age range satisfies all configured age gates.
  case verified = 0
  /// The platform could not produce an age signal.
  ///
  /// Common reasons:
  /// - Parental controls are not configured (Android)
  /// - Verification data is unavailable for this account
  /// - The API is unsupported in the user's region
  case unknown = 1
  /// The user chose not to share their age (iOS only).
  ///
  /// The user was prompted but explicitly declined to reveal their age
  /// range to the app.
  case declined = 2
  /// The user is below the age threshold or under parental supervision.
  ///
  /// Android: the account is family-managed and does not meet the age
  /// requirement. iOS: the declared age range falls below the configured gates.
  case supervised = 3
  /// Supervised user — guardian approval is pending (Android only).
  ///
  /// The account is family-managed and an access request has been dispatched
  /// to the guardian. The guardian has not yet responded.
  case supervisedApprovalPending = 4
  /// Supervised user — guardian denied the request (Android only).
  ///
  /// The account is family-managed and the guardian has explicitly
  /// rejected the access request.
  case supervisedApprovalDenied = 5
  /// Age was self-declared through Google Play (Android only).
  ///
  /// The user completed Google Play's age declaration flow.
  /// Requires age-signals 0.0.3 or later.
  case declared = 6
}

/// Who provided the age declaration (iOS only).
enum AgeDeclarationSource: Int {
  /// The user declared their own age.
  case selfDeclared = 0
  /// A guardian declared the age on the user's behalf via Family Sharing.
  case guardianDeclared = 1
}

/// Error codes reported when an age verification call fails.
enum AgeVerificationErrorCode: Int {
  /// The Age Signals API is not available on this device or region.
  case apiNotAvailable = 0
  /// Google Play Services encountered an error.
  case playServicesError = 1
  /// A network error prevented the request from completing.
  case networkError = 2
  /// The installed Play Services SDK is too old to support Age Signals.
  case sdkVersionOutdated = 3
  /// [AgeVerificationApi.verifyAge] was called before [AgeVerificationApi.initialize].
  case notInitialized = 4
  /// An unexpected error occurred during initialisation.
  case initError = 5
  /// An unclassified API error occurred.
  case apiError = 6
}

/// Mock result returned by [AgeVerificationApi.verifyAge] during testing.
///
/// Pass to [AgeVerificationApi.initialize] to enable mock mode on both
/// platforms. The native API is not called — [verifyAge] returns this data
/// directly. Pass `null` to [initialize] for real production behaviour.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AgeVerificationMockConfig: Hashable {
  /// The status to return from [AgeVerificationApi.verifyAge].
  var status: AgeSignalsStatus
  /// Mocked inclusive lower bound of the age range.
  var ageLower: Int64? = nil
  /// Mocked inclusive upper bound of the age range.
  var ageUpper: Int64? = nil
  /// Mocked declaration source (iOS field).
  var source: AgeDeclarationSource? = nil
  /// Mocked install identifier (Android field).
  var installId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AgeVerificationMockConfig? {
    let status = pigeonVar_list[0] as! AgeSignalsStatus
    let ageLower: Int64? = nilOrValue(pigeonVar_list[1])
    let ageUpper: Int64? = nilOrValue(pigeonVar_list[2])
    let source: AgeDeclarationSource? = nilOrValue(pigeonVar_list[3])
    let installId: String? = nilOrValue(pigeonVar_list[4])

    return AgeVerificationMockConfig(
      status: status,
      ageLower: ageLower,
      ageUpper: ageUpper,
      source: source,
      installId: installId
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      ageLower,
      ageUpper,
      source,
      installId,
    ]
  }
  static func == (lhs: AgeVerificationMockConfig, rhs: AgeVerificationMockConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgeVerificationApi(lhs.status, rhs.status) && deepEqualsAgeVerificationApi(lhs.ageLower, rhs.ageLower) && deepEqualsAgeVerificationApi(lhs.ageUpper, rhs.ageUpper) && deepEqualsAgeVerificationApi(lhs.source, rhs.source) && deepEqualsAgeVerificationApi(lhs.installId, rhs.installId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AgeVerificationMockConfig")
    deepHashAgeVerificationApi(value: status, hasher: &hasher)
    deepHashAgeVerificationApi(value: ageLower, hasher: &hasher)
    deepHashAgeVerificationApi(value: ageUpper, hasher: &hasher)
    deepHashAgeVerificationApi(value: source, hasher: &hasher)
    deepHashAgeVerificationApi(value: installId, hasher: &hasher)
  }
}

/// Data returned by the platform after querying age signals.
///
/// Wraps the raw response from the native age verification API.
/// Fields vary by platform; expect nulls where a platform does not
/// provide a particular value or when the user withholds consent.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AgeVerificationResult: Hashable {
  /// The outcome of the age check as reported by the platform.
  var status: AgeSignalsStatus
  /// Inclusive lower bound of the estimated age range.
  ///
  /// iOS: present when the user grants permission to share their age bracket.
  /// Android: present for family-managed accounts via parental controls.
  /// Null when the user opts out (iOS) or the platform cannot supply the value.
  var ageLower: Int64? = nil
  /// Inclusive upper bound of the estimated age range.
  ///
  /// iOS: present when the user grants permission to share their age bracket.
  /// Android: present for family-managed accounts via parental controls.
  /// Null when the user opts out (iOS) or the platform cannot supply the value.
  var ageUpper: Int64? = nil
  /// Who provided the age declaration (iOS only).
  ///
  /// Distinguishes between an age declared by the user themselves and one
  /// entered by a guardian through Family Sharing. Null on Android or when
  /// the user has not shared their age.
  var source: AgeDeclarationSource? = nil
  /// Stable identifier for this app install (Android only).
  ///
  /// Intended for compliance logging and audit trails.
  /// Always null on iOS.
  var installId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AgeVerificationResult? {
    let status = pigeonVar_list[0] as! AgeSignalsStatus
    let ageLower: Int64? = nilOrValue(pigeonVar_list[1])
    let ageUpper: Int64? = nilOrValue(pigeonVar_list[2])
    let source: AgeDeclarationSource? = nilOrValue(pigeonVar_list[3])
    let installId: String? = nilOrValue(pigeonVar_list[4])

    return AgeVerificationResult(
      status: status,
      ageLower: ageLower,
      ageUpper: ageUpper,
      source: source,
      installId: installId
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      ageLower,
      ageUpper,
      source,
      installId,
    ]
  }
  static func == (lhs: AgeVerificationResult, rhs: AgeVerificationResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAgeVerificationApi(lhs.status, rhs.status) && deepEqualsAgeVerificationApi(lhs.ageLower, rhs.ageLower) && deepEqualsAgeVerificationApi(lhs.ageUpper, rhs.ageUpper) && deepEqualsAgeVerificationApi(lhs.source, rhs.source) && deepEqualsAgeVerificationApi(lhs.installId, rhs.installId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AgeVerificationResult")
    deepHashAgeVerificationApi(value: status, hasher: &hasher)
    deepHashAgeVerificationApi(value: ageLower, hasher: &hasher)
    deepHashAgeVerificationApi(value: ageUpper, hasher: &hasher)
    deepHashAgeVerificationApi(value: source, hasher: &hasher)
    deepHashAgeVerificationApi(value: installId, hasher: &hasher)
  }
}

private class AgeVerificationApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AgeSignalsStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AgeDeclarationSource(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AgeVerificationErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return AgeVerificationMockConfig.fromList(self.readValue() as! [Any?])
    case 133:
      return AgeVerificationResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AgeVerificationApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AgeSignalsStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AgeDeclarationSource {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? AgeVerificationErrorCode {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? AgeVerificationMockConfig {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AgeVerificationResult {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AgeVerificationApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AgeVerificationApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AgeVerificationApiPigeonCodecWriter(data: data)
  }
}

class AgeVerificationApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AgeVerificationApiPigeonCodec(readerWriter: AgeVerificationApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AgeVerificationApi {
  /// Initializes the platform age signals manager.
  ///
  /// Pass [mockConfig] to enable mock mode — both platforms will return the
  /// supplied result from [verifyAge] without calling the native API.
  /// Omit [mockConfig] (or pass null) for real production behaviour.
  func initialize(mockConfig: AgeVerificationMockConfig?, completion: @escaping (Result<Void, Error>) -> Void)
  func verifyAge(ageGates: [Int64]?, completion: @escaping (Result<AgeVerificationResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AgeVerificationApiSetup {
  static var codec: FlutterStandardMessageCodec { AgeVerificationApiPigeonCodec.shared }
  /// Sets up an instance of `AgeVerificationApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AgeVerificationApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initializes the platform age signals manager.
    ///
    /// Pass [mockConfig] to enable mock mode — both platforms will return the
    /// supplied result from [verifyAge] without calling the native API.
    /// Omit [mockConfig] (or pass null) for real production behaviour.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.age_verification.AgeVerificationApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mockConfigArg: AgeVerificationMockConfig? = nilOrValue(args[0])
        api.initialize(mockConfig: mockConfigArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let verifyAgeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.age_verification.AgeVerificationApi.verifyAge\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      verifyAgeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let ageGatesArg: [Int64]? = nilOrValue(args[0])
        api.verifyAge(ageGates: ageGatesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      verifyAgeChannel.setMessageHandler(nil)
    }
  }
}
