// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.gtirkha.age_verification.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AgeVerificationApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Outcome of an age verification request. */
enum class AgeVerificationStatus(val raw: Int) {
  /**
   * The platform confirms the user meets the minimum age requirement.
   *
   * Android: parental controls indicate the account is above the threshold.
   * iOS: the declared age range satisfies all configured age gates.
   */
  VERIFIED(0),
  /**
   * The platform could not produce an age signal.
   *
   * Common reasons:
   * - Parental controls are not configured (Android)
   * - Verification data is unavailable for this account
   * - The API is unsupported in the user's region
   */
  UNKNOWN(1),
  /**
   * The user chose not to share their age (iOS only).
   *
   * The user was prompted but explicitly declined to reveal their age
   * range to the app.
   */
  DECLINED(2),
  /**
   * The user is below the age threshold or under parental supervision.
   *
   * Android: the account is family-managed and does not meet the age
   * requirement. iOS: the declared age range falls below the configured gates.
   */
  SUPERVISED(3),
  /**
   * Supervised user — guardian approval is pending (Android only).
   *
   * The account is family-managed and an access request has been dispatched
   * to the guardian. The guardian has not yet responded.
   */
  SUPERVISED_APPROVAL_PENDING(4),
  /**
   * Supervised user — guardian denied the request (Android only).
   *
   * The account is family-managed and the guardian has explicitly
   * rejected the access request.
   */
  SUPERVISED_APPROVAL_DENIED(5),
  /**
   * Age was self-declared through Google Play (Android only).
   *
   * The user completed Google Play's age declaration flow.
   * Requires age-signals 0.0.3 or later.
   */
  DECLARED(6);

  companion object {
    fun ofRaw(raw: Int): AgeVerificationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Who provided the age declaration (iOS only). */
enum class AgeDeclarationSource(val raw: Int) {
  /** The user declared their own age. */
  SELF_DECLARED(0),
  /** A guardian declared the age on the user's behalf via Family Sharing. */
  GUARDIAN_DECLARED(1);

  companion object {
    fun ofRaw(raw: Int): AgeDeclarationSource? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Error codes reported when an age verification call fails.
 *
 * The Android-specific values mirror Google Play's
 * `AgeSignalsErrorCode` 1:1 so callers can react to the exact
 * underlying condition instead of a lumped-together bucket.
 */
enum class AgeVerificationErrorCode(val raw: Int) {
  /**
   * The Age Signals API is not available on this device or region.
   *
   * Android: `AgeSignalsErrorCode.API_NOT_AVAILABLE`. The Play Store app
   * version installed on the device might be old; ask the user to update it.
   */
  API_NOT_AVAILABLE(0),
  /**
   * No Play Store app is found on the device (Android only).
   *
   * Android: `AgeSignalsErrorCode.PLAY_STORE_NOT_FOUND`. Ask the user to
   * install or enable the Play Store.
   */
  PLAY_STORE_NOT_FOUND(1),
  /** A network error prevented the request from completing. */
  NETWORK_ERROR(2),
  /**
   * Play Services is not available or its version is too old (Android only).
   *
   * Android: `AgeSignalsErrorCode.PLAY_SERVICES_NOT_FOUND`. Ask the user to
   * install, update, or enable Play Services.
   */
  PLAY_SERVICES_NOT_FOUND(3),
  /**
   * Binding to the service in the Play Store failed (Android only).
   *
   * Android: `AgeSignalsErrorCode.CANNOT_BIND_TO_SERVICE`. Can be caused by
   * an old Play Store version or an overloaded device; retry with backoff.
   */
  CANNOT_BIND_TO_SERVICE(4),
  /**
   * The Play Store app needs to be updated (Android only).
   *
   * Android: `AgeSignalsErrorCode.PLAY_STORE_VERSION_OUTDATED`.
   */
  PLAY_STORE_VERSION_OUTDATED(5),
  /**
   * Play Services needs to be updated (Android only).
   *
   * Android: `AgeSignalsErrorCode.PLAY_SERVICES_VERSION_OUTDATED`.
   */
  PLAY_SERVICES_VERSION_OUTDATED(6),
  /**
   * A transient error occurred on the client device (Android only).
   *
   * Android: `AgeSignalsErrorCode.CLIENT_TRANSIENT_ERROR`. Retry with a
   * capped number of attempts before giving up.
   */
  CLIENT_TRANSIENT_ERROR(7),
  /**
   * The app was not installed by Google Play (Android only).
   *
   * Android: `AgeSignalsErrorCode.APP_NOT_OWNED`. Ask the user to get the
   * app from Google Play.
   */
  APP_NOT_OWNED(8),
  /**
   * The installed Play Services SDK is too old to support Age Signals.
   *
   * Android: `AgeSignalsErrorCode.SDK_VERSION_OUTDATED`.
   */
  SDK_VERSION_OUTDATED(9),
  /**
   * An unknown internal error occurred (Android only).
   *
   * Android: `AgeSignalsErrorCode.INTERNAL_ERROR`. Retry with a capped
   * number of attempts; if it persists, contact Play Developer support.
   */
  INTERNAL_ERROR(10),
  /** [AgeVerificationApi.verifyAge] was called before [AgeVerificationApi.initialize]. */
  NOT_INITIALIZED(11),
  /** An unexpected error occurred during initialisation. */
  INIT_ERROR(12),
  /** An unclassified API error occurred. */
  API_ERROR(13);

  companion object {
    fun ofRaw(raw: Int): AgeVerificationErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Mock result returned by [AgeVerificationApi.verifyAge] during testing.
 *
 * Pass to [AgeVerificationApi.initialize] to enable mock mode on both
 * platforms. The native API is not called — [verifyAge] returns this data
 * directly. Pass `null` to [initialize] for real production behaviour.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AgeVerificationMockConfig (
  /** The status to return from [AgeVerificationApi.verifyAge]. */
  val status: AgeVerificationStatus,
  /** Mocked inclusive lower bound of the age range. */
  val ageLower: Long? = null,
  /** Mocked inclusive upper bound of the age range. */
  val ageUpper: Long? = null,
  /** Mocked declaration source (iOS field). */
  val source: AgeDeclarationSource? = null,
  /** Mocked install identifier (Android field). */
  val installId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AgeVerificationMockConfig {
      val status = pigeonVar_list[0] as AgeVerificationStatus
      val ageLower = pigeonVar_list[1] as Long?
      val ageUpper = pigeonVar_list[2] as Long?
      val source = pigeonVar_list[3] as AgeDeclarationSource?
      val installId = pigeonVar_list[4] as String?
      return AgeVerificationMockConfig(status, ageLower, ageUpper, source, installId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      ageLower,
      ageUpper,
      source,
      installId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AgeVerificationMockConfig
    return AgeVerificationApiPigeonUtils.deepEquals(this.status, other.status) && AgeVerificationApiPigeonUtils.deepEquals(this.ageLower, other.ageLower) && AgeVerificationApiPigeonUtils.deepEquals(this.ageUpper, other.ageUpper) && AgeVerificationApiPigeonUtils.deepEquals(this.source, other.source) && AgeVerificationApiPigeonUtils.deepEquals(this.installId, other.installId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AgeVerificationApiPigeonUtils.deepHash(this.status)
    result = 31 * result + AgeVerificationApiPigeonUtils.deepHash(this.ageLower)
    result = 31 * result + AgeVerificationApiPigeonUtils.deepHash(this.ageUpper)
    result = 31 * result + AgeVerificationApiPigeonUtils.deepHash(this.source)
    result = 31 * result + AgeVerificationApiPigeonUtils.deepHash(this.installId)
    return result
  }
}

/**
 * Data returned by the platform after querying age signals.
 *
 * Wraps the raw response from the native age verification API.
 * Fields vary by platform; expect nulls where a platform does not
 * provide a particular value or when the user withholds consent.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AgeVerificationResult (
  /** The outcome of the age check as reported by the platform. */
  val status: AgeVerificationStatus,
  /**
   * Inclusive lower bound of the estimated age range.
   *
   * iOS: present when the user grants permission to share their age bracket.
   * Android: present for family-managed accounts via parental controls.
   * Null when the user opts out (iOS) or the platform cannot supply the value.
   */
  val ageLower: Long? = null,
  /**
   * Inclusive upper bound of the estimated age range.
   *
   * iOS: present when the user grants permission to share their age bracket.
   * Android: present for family-managed accounts via parental controls.
   * Null when the user opts out (iOS) or the platform cannot supply the value.
   */
  val ageUpper: Long? = null,
  /**
   * Who provided the age declaration (iOS only).
   *
   * Distinguishes between an age declared by the user themselves and one
   * entered by a guardian through Family Sharing. Null on Android or when
   * the user has not shared their age.
   */
  val source: AgeDeclarationSource? = null,
  /**
   * Stable identifier for this app install (Android only).
   *
   * Intended for compliance logging and audit trails.
   * Always null on iOS.
   */
  val installId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AgeVerificationResult {
      val status = pigeonVar_list[0] as AgeVerificationStatus
      val ageLower = pigeonVar_list[1] as Long?
      val ageUpper = pigeonVar_list[2] as Long?
      val source = pigeonVar_list[3] as AgeDeclarationSource?
      val installId = pigeonVar_list[4] as String?
      return AgeVerificationResult(status, ageLower, ageUpper, source, installId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      ageLower,
      ageUpper,
      source,
      installId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AgeVerificationResult
    return AgeVerificationApiPigeonUtils.deepEquals(this.status, other.status) && AgeVerificationApiPigeonUtils.deepEquals(this.ageLower, other.ageLower) && AgeVerificationApiPigeonUtils.deepEquals(this.ageUpper, other.ageUpper) && AgeVerificationApiPigeonUtils.deepEquals(this.source, other.source) && AgeVerificationApiPigeonUtils.deepEquals(this.installId, other.installId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AgeVerificationApiPigeonUtils.deepHash(this.status)
    result = 31 * result + AgeVerificationApiPigeonUtils.deepHash(this.ageLower)
    result = 31 * result + AgeVerificationApiPigeonUtils.deepHash(this.ageUpper)
    result = 31 * result + AgeVerificationApiPigeonUtils.deepHash(this.source)
    result = 31 * result + AgeVerificationApiPigeonUtils.deepHash(this.installId)
    return result
  }
}
private open class AgeVerificationApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AgeVerificationStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AgeDeclarationSource.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AgeVerificationErrorCode.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AgeVerificationMockConfig.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AgeVerificationResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AgeVerificationStatus -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is AgeDeclarationSource -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is AgeVerificationErrorCode -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is AgeVerificationMockConfig -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is AgeVerificationResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AgeVerificationApi {
  /**
   * Initializes the platform age signals manager.
   *
   * Pass [mockConfig] to enable mock mode — both platforms will return the
   * supplied result from [verifyAge] without calling the native API.
   * Omit [mockConfig] (or pass null) for real production behaviour.
   */
  fun initialize(mockConfig: AgeVerificationMockConfig?, callback: (Result<Unit>) -> Unit)
  /**
   * Queries the platform for age signals and returns the result.
   *
   * [ageGates] is an optional list of age thresholds (e.g. `[13, 18]`) used
   * on iOS to determine which age bracket the user falls into. Android ignores
   * this parameter — age ranges are determined by Google Play parental controls.
   *
   * [skipEligibilityCheck] bypasses the `isEligibleForAgeFeatures` check on
   * iOS 26.2+. When `true`, `requestAgeRange` is called directly without first
   * awaiting `isEligibleForAgeFeatures` — useful if you experience hangs or
   * unreliable results from that API in your region. Has no effect on Android.
   * Defaults to `false` (existing behavior).
   */
  fun verifyAge(ageGates: List<Long>?, skipEligibilityCheck: Boolean, callback: (Result<AgeVerificationResult>) -> Unit)

  companion object {
    /** The codec used by AgeVerificationApi. */
    val codec: MessageCodec<Any?> by lazy {
      AgeVerificationApiPigeonCodec()
    }
    /** Sets up an instance of `AgeVerificationApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AgeVerificationApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.age_verification.AgeVerificationApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mockConfigArg = args[0] as AgeVerificationMockConfig?
            api.initialize(mockConfigArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AgeVerificationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(AgeVerificationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.age_verification.AgeVerificationApi.verifyAge$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ageGatesArg = args[0] as List<Long>?
            val skipEligibilityCheckArg = args[1] as Boolean
            api.verifyAge(ageGatesArg, skipEligibilityCheckArg) { result: Result<AgeVerificationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AgeVerificationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AgeVerificationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
